### ISSUE TITLE
Exporting for both X and Y coordinates is not working

### ISSUE THREAD

**Issue by nagyabelmihaly** [flochkristof/motiontracker#1]
Only the half of the tracked objects are exported when both X and Y coordinates are exported, the other values are zero, and the last nonzero value is with negative sign:
![image](https://user-images.githubusercontent.com/42240320/208652171-4c2dedd3-68d7-41c4-83a9-efbb0c16f39b.png)
My tracked objects are like this:
![image](https://user-images.githubusercontent.com/42240320/208652266-fa989494-2f18-4a10-910c-f6f86a8f10f8.png)

**Comment by flochkristof** [comment]
fixed in v0.1.3
